#pragma config(Motor,  port6,           dr1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           dr2,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           dl1,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           dl2,           tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  ____ _                 _          __  __             _
 / ___| |__  _   _ _ __ | | ___   _|  \/  | ___  _ __ | | _____ _   _
| |   | '_ \| | | | '_ \| |/ / | | | |\/| |/ _ \| '_ \| |/ / _ \ | | |
| |___| | | | |_| | | | |   <| |_| | |  | | (_) | | | |   <  __/ |_| |
 \____|_| |_|\__,_|_| |_|_|\_\\__, |_|  |_|\___/|_| |_|_|\_\___|\__, |
                              |___/                             |___/
MiniMBP:~ matt$
Weston Middle School
*/

task main()	{

	while (true) {


		// Used to filter out joystick abberations
		int threshold = 10;

		//////////////////////////////////////////////////////////
		//
		// DRIVE
		//
		// This code has filtering in place
		// Because the joystick returns a value that is not always
		// exactly zero.
		//
		// Because of this, the Cortex makes a whining sound
		// because the drive motors are being triggered
		// with values less than 10
		//
		// By testing if the joystick is within the threshold
		// We can turn off the motors and stop the noise
		// and power drain

		if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
		{
			motor[dl1]  = (vexRT[Ch3] );
			motor[dl2]  = (vexRT[Ch3] );
		}
		else                                    // If the left joystick is within the threshold:
		{
			motor[dl1]  = (0);
			motor[dl2]  = (0 );
		}

		if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
		{
			motor[dr1] = (vexRT[Ch2]);
			motor[dr2] = (vexRT[Ch2]);

		}
		else                                    // If the right joystick is within the threshold:
		{
			motor[dr1] = 0;                // Stop the right motor (cancel noise)
			motor[dr2] = 0;
		}

	}
}
