#pragma config(Motor,  port1,           dr2,           tmotorNone, openLoop)
#pragma config(Motor,  port2,           lift1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           lift2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           lift1b,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           lift2b,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           dr1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           dl1,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          dl2,           tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* MiniMBP:~ matt$
Weston Middle School
*/



task liftCheckUp()
{
	if(vexRT[Btn6U]==1)
	{
		motor[lift1]=120;
		motor[lift1b]=120;//Raises lift whBtn6U is pressed
		motor[lift2]=120;
		motor[lift2b]=120;
	}
	else if(vexRT[Btn6U]==0 && vexRT [Btn6D]==0)
	{
		motor[lift1]=0;
		motor[lift1b]=0;//Stop thrower
		motor[lift2]=0;
		motor[lift2b]=0;
	}
}

task liftCheckDown()
{
	if(vexRT[Btn6D]==1)
	{
		motor[lift1]=-100;
		motor[lift1b]=-100;//lowers lift while 6D is pressed
		motor[lift2]=-100;
		motor[lift2]=-100;
	}
	else if(vexRT[Btn5D]==0 && vexRT[Btn5U]==0)
	{
		motor[lift1]=0;
		motor[lift1b]=0;//Stop thrower
		motor[lift2]=0;
		motor[lift2b]=0;
	}
}


task main()	{
 		while (true) {
		// Used to filter out joystick abberations
		int threshold = 10;
		//////////////////////////////////////////////////////////
		//
		// DRIVE
		//
		// This code has filtering in place
		// Because the joystick returns a value that is not always
		// exactly zero.
		//
		// Because of this, the Cortex makes a whining sound
		// because the drive motors are being triggered
		// with values less than 10
		//
		// By testing if the joystick is within the threshold
		// We can turn off the motors and stop the noise
		// and power drain

		if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
		{
			motor[dl1]  = (vexRT[Ch3] );
			motor[dl2]  = (vexRT[Ch3] );
		}
		else                                    // If the left joystick is within the threshold:
		{
			motor[dl1]  = 0;
			motor[dl2]  = 0;
		}
		if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
		{
			motor[dr1] = (vexRT[Ch2]);
			motor[dr2] = (vexRT[Ch2]);
		}
		else                                    // If the right joystick is within the threshold:
		{
			motor[dr1] = 0;
			motor[dr2] = 0;                    // Stop the right motor (cancel noise)
		}


	startTask(liftCheckUp);

	startTask(liftCheckDown);

	}
}
