#pragma config(Motor,  port1,           frontRightMotor, tmotorNone, openLoop)
#pragma config(Motor,  port2,           forklifta,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           forkliftb,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           backRightMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           backLeftMotor, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          frontLeftMotor, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main()
{
  while(1 == 1)
  {
    //Right side of the robot is controlled by the right joystick, Y-axis
    motor[frontRightMotor] = vexRT[Ch2];
    motor[backRightMotor]  = vexRT[Ch2];
    //Left side of the robot is controlled by the left joystick, Y-axis
    motor[frontLeftMotor] = vexRT[Ch3];
    motor[backLeftMotor]  = vexRT[Ch3];

    if(vexRT[Btn6U]==1)
    {
    	motor[forklifta]=120;
    	motor[forkliftb]=120;
  	}

  	if (vexRT[Btn6D]==1)
  	{
  		motor[forklifta]=-120;
  		motor[forkliftb]=-120;
  	}
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
