#pragma config(Motor,  port2,           forklift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mthrower1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mthrower2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           dr1,           tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           dl1,           tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* MiniMBP:~ matt$
Weston Middle School
*/

task forkliftCheckUp()
{
	if(vexRT[Btn6U]==1)
	{
		motor[forklift]=120; //Raises forklift while 6U is pressed
	}
	else if(vexRT[Btn6U]==0 && vexRT[Btn6D]==0)
	{
		motor[forklift]=0; //Stop thrower
	}

}

task forkliftCheckDown()
{
		if(vexRT[Btn6D]==1)
	{
		motor[forklift]=-120; //Lowers forklift while 6D is pressed
	}
	else if(vexRT[Btn6D]==0 && vexRT[Btn6U]==0)
	{
		motor[forklift]=0; //Stop thrower
	}
}

task mthrowerCheckUp()
{
	if(vexRT[Btn7U]==1)
	{
		motor[mthrower1]=120; //Raises thrower whBtn5U is pressed
		motor[mthrower2]=120;
	}
	else if(vexRT[Btn7U]==0 && vexRT[Btn7D]==0)
	{
		motor[mthrower1]=0; //Stop thrower
		motor[mthrower2]=0;
	}
}

task mthrowerCheckDown()
{
	if(vexRT[Btn5D]==1)
	{
		motor[mthrower1]=-120; //Raises thrower while 5D is pressed
		motor[mthrower2]=-120;
	}
	else if(vexRT[Btn5D]==0 && vexRT[Btn5U]==0)
	{
		motor[mthrower1]=0; //Stop thrower
		motor[mthrower2]=0;
	}
}


task main()	{
 		while (true) {
		// Used to filter out joystick abberations
		int threshold = 10;
		//////////////////////////////////////////////////////////
		//
		// DRIVE
		//
		// This code has filtering in place
		// Because the joystick returns a value that is not always
		// exactly zero.
		//
		// Because of this, the Cortex makes a whining sound
		// because the drive motors are being triggered
		// with values less than 10
		//
		// By testing if the joystick is within the threshold
		// We can turn off the motors and stop the noise
		// and power drain

		if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
		{
			motor[dl1]  = (vexRT[Ch3] );
		}
		else                                    // If the left joystick is within the threshold:
		{
			motor[dl1]  = (0);
		}
		if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
		{
			motor[dr1] = (vexRT[Ch2]);
		}
		else                                    // If the right joystick is within the threshold:
		{
			motor[dr1] = 0;                // Stop the right motor (cancel noise)
		}

	startTask(forkliftCheckUp);

	startTask(forkliftCheckDown);

	startTask(mthrowerCheckUp);

	startTask(mthrowerCheckDown);

	}
}
