#pragma config(Motor,  port2,           forklift,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mthrower1,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mthrower2,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           dr1,           tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,           dl1,           tmotorVex269_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Created by Ash Rajesh, Jack Aaron,
Weston Middle School
*/
task drive()
{
	// Used to filter out joystick abberations
		int threshold = 10;

		if(abs(vexRT[Ch3]) > threshold)         // If the left joystick is greater than or less than the threshold:
		{
			motor[dl1]  = (vexRT[Ch3] );
		}
		else                                    // If the left joystick is within the threshold:
		{
			motor[dl1]  = (0);
		}
		if(abs(vexRT[Ch2]) > threshold)         // If the right joystick is greater than or less than the threshold:
		{
			motor[dr1] = (vexRT[Ch2]);
		}
		else                                    // If the right joystick is within the threshold:
		{
			motor[dr1] = 0;                // Stop the right motor (cancel noise)
		}

}
// Main

task main()
{

	while (true)
	{

		startTask(drive);

		//Forklift

		while(vexRT[Btn6U]==1) //When 6U is pressed
		{
			motor[forklift]=120; //Turn on forklift
		}

		motor[forklift]=0; //Turn off forklift

		while(vexRT[Btn6D]==1)//When 6D is pressed
		{
			motor[forklift]=-120; //Turn on forklift(reversed)
		}

		motor[forklift]=0; //Turn off forklift

		//Thrower

		while(vexRT[Btn7U]==1) //When 7U is pressed
		{
			motor[mthrower1]=120; //Turn on thrower
			motor[mthrower2]=120;
		}

		motor[mthrower1]=0; //Turn off thrower
		motor[mthrower2]=0;

		while(vexRT[Btn7U]==1) //When 7U is pressed
		{
			motor[mthrower1]=120; //Turn on thrower(reversed)
			motor[mthrower2]=120;
		}

		motor[mthrower1]=0; //Turn off thrower
		motor[mthrower2]=0;


			while(vexRT[Btn7D]==1) //When 7D is pressed
		{
			motor[mthrower1]=-120; //Turn on thrower(reversed)
			motor[mthrower2]=-120;
		}

		motor[mthrower1]=0; //Turn off thrower
		motor[mthrower2]=0;
	}


}

