#pragma config(Motor,  port1,           dr,            tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           stl,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           sbl,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           str,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           sbr,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           intakefront,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           intakeback,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           m8,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           m9,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          dl,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
____           ______ _ _
| __ ) _ __ ___|__  (_) | | __ _
|  _ \| '__/ _ \ / /| | | |/ _` |_____
| |_) | | | (_) / /_| | | | (_| |_____|
|____/|_|  \___/____|_|_|_|\__,_|
_         _       ____  _             _
/ \  _   _| |_ ___/ ___|| |_ __ _ _ __| |_
/ _ \| | | | __/ _ \___ \| __/ _` | '__| __|
/ ___ \ |_| | || (_) |__) | || (_| | |  | |_
/_/   \_\__,_|\__\___/____/ \__\__,_|_|   \__|



Team Error 404
Weston Middle School
*/


//////////////////////////////////////////////////////////
//
// FUNCTIONS
//


void shooterMotors(int speed) {
	motor[stl] = speed;
	motor[sbl] = speed;
	motor[str] = speed;
	motor[sbr] = speed;
}

void intakeMotors(int speed) {
	motor[intakefront] = speed;
	motor[intakeback] = speed;
}


task main()	{


	//////////////////////////////////////////////////////////
	//
	// CONFIGURATION
	//


	int shooterSpeed = 127;
	int autoStart = 1;



	while (true) {

		// Run this until autoStart is 0
		if (autoStart == 1) {
			shooterMotors(shooterSpeed);
			intakeMotors(127);

			// Exit AutoStart Mode when button is pressed
			// Turn off Elevator
			// Leave shooters on

			if (vexRT[Btn8U] == 1) {
				intakeMotors(0);
				autoStart = 0;
			}
		}


		// Used to filter out joystick abberations
		int threshold = 10;

		//////////////////////////////////////////////////////////
		//
		// DRIVE
		//
		// This code has filtering in place
		// Because the joystick returns a value that is not always
		// exactly zero.

		if(abs(vexRT[Ch3]) > threshold)
		{
			motor[dl]  = (vexRT[Ch3] );
		}
		else
		{
			motor[dl]  = 0;
		}

		if(abs(vexRT[Ch2]) > threshold)
		{
			motor[dr] = (vexRT[Ch2]);
		}
		else
		{
			motor[dr] = 0;
		}

	//////////////////////////////////////////////////////////
	//
	// SHOOTERS
	//

		if (vexRT[Btn6U] == 1) {
			shooterMotors(shooterSpeed);
			} else {
			shooterMotors(0);
		}

	//////////////////////////////////////////////////////////
	//
	// INTAKE MECHANISM
	//

		if (vexRT[Btn5U] == 1) {
			intakeMotors(127);
			} else {

			// If 5U isn't pressed
			// check for 5D which is
			// reverse. If neither, turn off.

			if (vexRT[Btn5D] == 1) {
				intakeMotors(-127);
				} else {

				// No buttons pressed? Stop motors
				intakeMotors(0);
			}
		}
	}
}
