#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           m2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           m3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           m4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           m5,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           m6,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           m7,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           m8,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           m9,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          m10,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{


	// Test program to spin motors 1-5 forward and 6-10 in reverse at full speed.

	while (1) {
		motor[m1] = 127;
		motor[m2] = 127;
		motor[m3] = 127;
		motor[m4] = 127;
		motor[m5] = 127;
		motor[m6] = 127;
		motor[m7] = 127;
		motor[m8] = 127;
		motor[m9] = 127;
		motor[m10] = 127;
	}

}
