#pragma config(Motor,  port1,           collectleft,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           elevateleft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           driverightback, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           driveleftfront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           shootleft, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           shootright,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveleftback,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           driverightfront,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           elevateright,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          collectright,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
__        ____  __ ____     ____
\ \      / /  \/  / ___|   / ___|___  _ __ ___
\ \ /\ / /| |\/| \___ \  | |   / _ \| '__/ _ \
\ V  V / | |  | |___) | | |__| (_) | | |  __/
\_/\_/  |_|  |_|____/   \____\___/|_|  \___|
*/

task main()	{

	while (true) {

		//////////////////////////////////////////////////////////
		//
		// DRIVE
		//


		// RIGHT SIDE

		motor[driverightback] = vexRT[Ch2];
		motor[driverightfront] = vexRT[Ch2];

		// LEFT SIDE

		motor[driveleftfront] = vexRT[Ch3];
		motor[driveleftback] = vexRT[Ch3];


		//////////////////////////////////////////////////////////
		//
		// COLLECTOR MECHANISM
		//

		// motors: collectleft, collectright
		//
		// Press 5U for foward. Release to stop
		// Press 5D for reverse. Release to stop
		// motors: collectleft & collectright

		// TODO: Validate that each motor is spinning in the correct direction
		//       If only one motor is needed, remove code for second motor

		if (vexRT[Btn5U] == 1) {
			motor[collectleft] = 127;
			motor[collectright] = 127;
		}
		else {
			motor[collectleft] = 0;
			motor[collectright] = 0;
		}

		if (vexRT[Btn5D] == 1) {
			motor[collectleft] = -127;
			motor[collectright] = -127;
		}
		else {
			motor[collectleft] = 0;
			motor[collectright] = 0;
		}


		//////////////////////////////////////////////////////////
		//
		// ELEVATOR
		//
		// Press 6U for foward. Release to stop
		// Press 6D for reverse. Release to stop
		// motors: elevateleft & elevateright


		if (vexRT[Btn6U] == 1) {
			motor[elevateleft] = 127;
			motor[elevateright] = 127;
		}
		else {
			motor[elevateleft] = 0;
			motor[elevateright] = 0;
		}

		if (vexRT[Btn6D] == 1) {
			motor[elevateleft] = -127;
			motor[elevateright] = -127;
		}
		else {
			motor[elevateleft] = 0;
			motor[elevateright] = 0;
		}


		//////////////////////////////////////////////////////////
		//
		// SHOOTER
		//
		// motors: shootleft, shootright

		// 7u to start
		// 7D to stop



		if (vexRT[Btn7U] == 1) {

			// Start the motors slowly

			// If Motor is not running, start it up
			if (motor[shootright] < 1) {
				int i;
				for (i=0; i<127; i=i+20) {
					motor[shootright] = i;
					motor[shootleft] = i;

					// Max out Motor speed
					if (i > 100) {
						i = 127;
					}
				}
			}
		}

		if (vexRT[Btn7D] == 1) {

			// TODO: Do we need slowdown code?

			motor[shootright] = 0;
			motor[shootleft] = 0;
		}


	} // END while (true)

} // END task main


/*
__        __        _                __  __ _     _     _ _
\ \      / /__  ___| |_ ___  _ __   |  \/  (_) __| | __| | | ___
 \ \ /\ / / _ \/ __| __/ _ \| '_ \  | |\/| | |/ _` |/ _` | |/ _ \
  \ V  V /  __/\__ \ || (_) | | | | | |  | | | (_| | (_| | |  __/
   \_/\_/ \___||___/\__\___/|_| |_| |_|  |_|_|\__,_|\__,_|_|\___|

There's No I in Team.

*/
