#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           m2,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           m3,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           m4,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           m5,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           m6,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           m7,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           m8,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           m9,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port10,          m10,           tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
_____         _   ____        _
|_   _|__  ___| |_| __ )  ___ | |_
| |/ _ \/ __| __|  _ \ / _ \| __|
| |  __/\__ \ |_| |_) | (_) | |_
|_|\___||___/\__|____/ \___/ \__|.c
*/
// Test program to spin motors 1-5 forward and 6-10 in reverse at full speed.

void spinMotors(int speed) {
		motor[m1] = speed;
		motor[m2] = speed;
		motor[m3] = speed;
		motor[m4] = speed;
		motor[m5] = speed;
		motor[m6] = speed;
		motor[m7] = speed;
		motor[m8] = speed;
		motor[m9] = speed;
		motor[m10] = speed;
}




task main()
{

	int motorSpeed = 127;

	while (1) {
		spinMotors(motorSpeed);
	}

}
