#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           m2,            tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
/*

  __                                  _
 / _| ___  _ ____      ____ _ _ __ __| |      _ __ _____   _____ _ __ ___  ___
| |_ / _ \| '__\ \ /\ / / _` | '__/ _` |_____| '__/ _ \ \ / / _ \ '__/ __|/ _ \
|  _| (_) | |   \ V  V / (_| | | | (_| |_____| | |  __/\ V /  __/ |  \__ \  __/
|_|  \___/|_|    \_/\_/ \__,_|_|  \__,_|     |_|  \___| \_/ \___|_|  |___/\___|

           _
        __| | ___ _ __ ___   ___
 _____ / _` |/ _ \ '_ ` _ \ / _ \
|_____| (_| |  __/ | | | | | (_) |
       \__,_|\___|_| |_| |_|\___/


*/
// Function to set motor speed. Pass in a zero to stop
//
// You can add or remove motors here

void spinMotors(int speed) {
	motor[m1] = speed;
	motor[m2] = speed;
}

task main()
{
	while (1) {

		// Buttons 5U and 5D are forward and reverse

		if (vexRT[Btn5U] == 1) {
			spinMotors(127);
			} else {

			// If 5U isn't pressed
			// check for 5D which is
			// reverse. If neither, turn off.

			if (vexRT[Btn5D] == 1) {
				spinMotors(-127);
				} else {

				// No buttons pressed? Stop motors
				spinMotors(0);
			}
		}

	}


}
