#pragma config(Motor,  port1,           m1,            tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
_____                 _   _             ____
|  ___|   _ _ __   ___| |_(_) ___  _ __ |  _ \  ___ _ __ ___   ___
| |_ | | | | '_ \ / __| __| |/ _ \| '_ \| | | |/ _ \ '_ ` _ \ / _ \
|  _|| |_| | | | | (__| |_| | (_) | | | | |_| |  __/ | | | | | (_) |
|_|   \__,_|_| |_|\___|\__|_|\___/|_| |_|____/ \___|_| |_| |_|\___/

Weston Middle School
*/

// The spinMotor function is defined outside of task main()
// can can be called within the code.
//
//


void spinMotor(int speed) {
	motor[m1] = speed;
}

task main()	{

	int motorSpeed = 127;

	while (true) {

		if (vexRT[Btn8U] == 1) {
			spinMotor(motorSpeed);
			} else {

			// If 5U isn't pressed
			// check for 5D which is
			// reverse. If neither, turn off.

			if (vexRT[Btn8U] == 1) {
				spinMotor(motorSpeed * -1);
				} else {

				// No buttons pressed? Stop motors
				intakeMotors(0);
			}
		}

	}
}
