#pragma config(Motor,	 port1,						collectleft,	 tmotorVex393_HBridge, openLoop)
#pragma config(Motor,	 port2,						elevateleft,	 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port3,						driverightback, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port4,						driveleftfront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port5,						shootL,				 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port6,						shootR,				 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port7,						driveleftback, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port8,						driverightfront, tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port9,						elevateright,	 tmotorVex393_MC29, openLoop)
#pragma config(Motor,	 port10,					collectright,	 tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard							 !!*//

/*
 _______  _______           _       _________ ______
(       )(  ___  )|\     /|( \      \__   __/(  ___ \
| () () || (   ) |( \   / )| (         ) (   | (   ) )
| || || || (___) | \ (_) / | |         | |   | (__/ /
| |(_)| ||  ___  |  ) _ (  | |         | |   |  __ (
| |   | || (   ) | / ( ) \ | |         | |   | (  \ \
| )   ( || )   ( |( /   \ )| (____/\___) (___| )___) )
|/     \||/     \||/     \|(_______/\_______/|/ \___/

*/

task main()	{

	while (true) {

		//////////////////////////////////////////////////////////
		//
		// DRIVE
		//
		//
		// RIGHT SIDE
		//
		// TODO: Write code to listen to Channel 2
		//			 move motors driverightfront and driverightback go forward and back
		//			 using analog joystick
		//
		//
		//
		// LEFT SIDE
		//
		// TODO: Write code to move Channel 3 forward and back
		//			 move motors driveleftfront and driveleftback
		//			 using analog joystick
		////////////////////////////////////////////////////////////

		motor[driveleftfront] = vexRT[Ch3];
		motor[driveleftback] = vexRT[Ch3];
		motor[driverightback] = vexRT[Ch2];
		motor[driverightfront] = vexRT[Ch2];



		///////////////////////////////////////////////////////////////
		//
		// COLLECTOR MECHANISM
		//
		//
		// motors: collectleft, collectright
		//
		//
		// TODO: Forward. Reverse. Stop.
		// Press 5U for foward. Release to stop
		// Press 5D for reverse. Release to stop
		// motors: collectleft & collectright
		//
		// POTENTIAL BUG! What happens if 5U and 5D are pressed at the same time
		//
		//
		// TODO: Validate that each motor is spinning in the correct direction
		//			 If only one motor is needed, remove code for second motor
		////////////////////////////////////////////////////////////////


		if (vexRT[Btn5U] == 1) {
			startMotor(collectright, 127);
			startMotor(collectleft, 127);
		}
		else {
			stopMotor(collectright);
			stopMotor(collectleft);
		}

		if (vexRT[Btn5D] == 1) {
			startMotor(collectright, -127);
			startMotor(collectleft, -127);
		}
		else {
			stopMotor(collectright);
			stopMotor(collectleft);
		}


		//////////////////////////////////////////////////////////
		//
		// ELEVATOR
		// TODO: Forward. Reverse. Stop.
		// Press 6U for foward. Release to stop
		// Press 6D for reverse. Release to stop
		// motors: elevateleft & elevateright
		////////////////////////////////////////////////////////////


		if (vexRT[Btn6U] == 1) {
			startMotor(elevateright, 127);
			startMotor(elevateleft, 127);
		}
		else {
			stopMotor(elevateright);
			stopMotor(elevateleft);
		}

		if (vexRT[Btn6D] == 1) {
			startMotor(elevateright, -127);
			startMotor(elevateleft, -127);
		}
		else {
			stopMotor(elevateright);
			stopMotor(elevateleft);
		}


		//////////////////////////////////////////////////////////
		//
		// SHOOTER
		//
		// motors: shootL, shootR
		//
		// todo: stop. start
		//				warmup code
		//
		// 7u to start
		// 7D to stop
		//////////////////////////////////////////////////////////


		if (vexRT[Btn7U] == 1) {


			// Start the motors slowly
	//		for (i=2; i<132; i++) {
				//writeDebugStream(i);

	//////////////////////////////////////////////////////////
	// backup launch startup code
		if(vexRT[Btn7U]==1) {
			motor[shootL]=15;
			motor[shootR]=15;
			wait10Msec(2);
			motor[shootL]=30;
			motor[shootR]=30;
			wait10Msec(2);
			motor[shootL]=50;
			motor[shootR]=50;
			wait10Msec(2);
			motor[shootL]=70;
			motor[shootR]=70;
			wait10Msec(2);
			motor[shootL]=95;
			motor[shootR]=95;
			wait10Msec(2);
			motor[shootL]=115;
			motor[shootR]=115;
			wait10Msec(2);
			motor[shootL]=127;
			motor[shootR]=127;
			wait10Msec(2);
	//////////////////////////////////////////////////////////




			}
		}


		if (vexRT[Btn7D] == 1) {

			// TODO: Do we need slowdown code?: NOPE

			stopMotor(shootR);
			stopMotor(shootL);
		}




	} // END while true
} // END task main



/*
__				__				_								 __	 __ _			_			_ _
\ \			 / /__	___| |_ ___	 _ __		|	 \/	 (_) __| | __| | | ___
 \ \ /\ / / _ \/ __| __/ _ \| '_ \	| |\/| | |/ _` |/ _` | |/ _ \
	\ V	 V /	__/\__ \ || (_) | | | | | |	 | | | (_| | (_| | |	__/
	 \_/\_/ \___||___/\__\___/|_| |_| |_|	 |_|_|\__,_|\__,_|_|\___|
There's No I in Team.

But there is also no I in myself... wierd bro

There's No Playground in Work

*/
